Controllers films users
MarchenkoDmitrii/java-filmorate pull request #4
Opened 2023-07-24 19:10 UTC by MarchenkoDmitrii

2023-07-25 22:28 UTC, PolnySkvorets requested changes
Посмотри замечания. В целом, окей, но по мелочам пропустил

2023-07-25 22:28 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Map<Integer, Film> films = new HashMap<>();
Добавь модификатор доступа

2023-07-25 22:28 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/films")
Вот это значение в скобках можно установить к аннотации @requestmapping над контроллером и не повторять это над каждым эндпоинтом

2023-07-25 22:28 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    Map<Integer, User> users = new HashMap<>();
Модификатор нужен

2023-07-25 22:28 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@lombok.Data
Здесь импорт можно поправить, оставив только @Data

2023-07-26 22:29 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +    public ValidationException(String cause, HttpStatus status) {
Вот здесь  status не используется никак, может его убрать или добавить логику?

2023-07-26 22:31 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (films.equals(null))
это условие никогда не выполнится, тем более даже если оно выполнится - упадёт  NPE, чтобы этого избежать, нужно объекты сравнивать безопасно, например Objects.equals(films, null)

2023-07-26 22:31 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().equals("") || film.getName().isEmpty())
нет проверки на  null, . можно поймать NPE

2023-07-26 22:32 UTC, PolnySkvorets requested changes
посмотри замечания по валидации

2023-07-27 03:48 UTC, MarchenkoDmitrii commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +    public ValidationException(String cause, HttpStatus status) {
В конструкторе она принимается, разве нет? Логика реализована в других классах для возможности использовать одно исключение во всех возможных случаях, например: 
``
  throw new ValidationException("логин не может быть пустым и содержать пробелы", HttpStatus.BAD_REQUEST);
  ``
Тут выводится причина прерывания и передается http статус

2023-07-27 14:21 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -        return films.values().stream().collect(Collectors.toList());
Да, так лучше, стримы нужны для фильтрации и преобразования данных

2023-07-27 14:22 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (Optional.ofNullable(user).isEmpty())
Здесь можно проще заменить на user == null

2023-07-27 14:22 UTC, PolnySkvorets requested changes
Посмотри одно замечание. Не нужно лишний раз использовать Optional, тут подойдёт обычное сравнение с null

2023-07-30 07:33 UTC, PolnySkvorets approved these changes
Всё отлично!

2023-07-30 07:35 UTC, merged