Add database
MarchenkoDmitrii/java-filmorate pull request #7
Opened 2023-09-08 17:29 UTC by MarchenkoDmitrii

2023-09-09 13:56 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    public Mpa(int id, String name) {
тебе не нужен дополнительный конструктор, он уже создастся аннотацией Data

2023-09-09 14:01 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbStorage/DbMpaStorage.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Нет такого фильма");
почему здесь выкладывается исключение, а в следующем запросе нет? Это один вопрос, второй : почему получение фильма происходит в сторадже Mpa,, лучше эту логику вынести на уровень сервиса. Каждое хранилище должно работать только с одной таблицей (или одной сущностью, если она состоит из нескольких таблиц)

2023-09-09 14:02 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        return filmDbStorage.getById(id);
Почему по методу getById получаем genre из filmDbStorage - нужно исправить имя поля

2023-09-09 14:03 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbStorage/UserDbStorage.java
> +@Component
Если есть аннотация Репозитория, то компонент уже не нужен, так как репозиторий уже является компонентом

2023-09-09 14:03 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/validate/FilmValidate.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "название не может быть пустым");
У остальных строк с описание ошибок первые буквы не заглавные

2023-09-09 14:05 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +                        (oldValue, newValue) -> oldValue, HashMap::new));
Вот здесь от сортировки ничего не останется, нужна treeMap или какя-нибудь из разновидностей sortedMap

2023-09-09 14:06 UTC, PolnySkvorets requested changes
привет! посмотри замечания, некоторые из них общие для нескольких классов, не стал дублировать везде

2023-09-09 16:05 UTC, MarchenkoDmitrii commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    public Mpa(int id, String name) {
java: constructor Genre in class ru.yandex.practicum.filmorate.model.Genre cannot be applied to given types;
При компиляции идеа ругается...

2023-09-09 16:16 UTC, MarchenkoDmitrii commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbStorage/DbMpaStorage.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Нет такого фильма");
Неправильно написана причина эксепшена(скопировал и не поменял), убрал отдельную строку для подсчета записей в таблице. Выкладывается исключение на первом запросе, потому-что запрос специальный и сделан только для того, чтобы смотреть есть ли определенная запись в таблице.

2023-09-09 16:16 UTC, MarchenkoDmitrii commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        return filmDbStorage.getById(id);
Исправил

2023-09-09 16:17 UTC, MarchenkoDmitrii commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbStorage/UserDbStorage.java
> +@Component
Исправил

2023-09-09 16:17 UTC, MarchenkoDmitrii commented on src/main/java/ru/yandex/practicum/filmorate/validate/FilmValidate.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "название не может быть пустым");
Исправил

2023-09-09 16:17 UTC, MarchenkoDmitrii commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +                        (oldValue, newValue) -> oldValue, HashMap::new));
Поменял на Treemap

2023-09-10 15:12 UTC, PolnySkvorets approved these changes
Всё исправлено, отлично

2023-09-10 19:04 UTC, merged